# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getEigenValues <- function(M) {
    .Call(`_scstruc_getEigenValues`, M)
}

row_replicate <- function(weight, rn) {
    .Call(`_scstruc_row_replicate`, weight, rn)
}

plasso_fit <- function(X, y, maxIter, lambda) {
    .Call(`_scstruc_plasso_fit`, X, y, maxIter, lambda)
}

