# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

row_replicate <- function(weight, rn) {
    .Call(`_scstruc_row_replicate`, weight, rn)
}

col_replicate <- function(weight, rn) {
    .Call(`_scstruc_col_replicate`, weight, rn)
}

plasso_fit <- function(X, y, maxIter, lambda, gamma, eps) {
    .Call(`_scstruc_plasso_fit`, X, y, maxIter, lambda, gamma, eps)
}

